name: test_actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: g++ hello.cpp -o hello
      - name: publish
        uses: actions/upload-artifact@v3
        with:
          path: hello
