name: test_actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: build
        uses: actions/checkout@v3
        with:
          cc: gcc
          cxx: g++
        run: pwd && ls && ls ../
